// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountCommentsByPost(ctx context.Context, postID int32) (int64, error)
	CountPosts(ctx context.Context) (int64, error)
	CountPostsByUser(ctx context.Context, userID int32) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (*Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (*Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteComment(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetCommentByID(ctx context.Context, id int32) (*GetCommentByIDRow, error)
	GetCommentsByPostID(ctx context.Context, postID int32) ([]*GetCommentsByPostIDRow, error)
	GetPostByID(ctx context.Context, id int32) (*GetPostByIDRow, error)
	GetPosts(ctx context.Context) ([]*GetPostsRow, error)
	GetPostsByUserID(ctx context.Context, userID int32) ([]*Post, error)
	GetPublishedPosts(ctx context.Context) ([]*GetPublishedPostsRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id int32) (*User, error)
	GetUsers(ctx context.Context) ([]*User, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (*Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (*Post, error)
	UpdatePostPublished(ctx context.Context, arg UpdatePostPublishedParams) (*Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
