// Auto-generated TypeScript types from Go structs
// Generated by: go run cmd/generate-types/main.go
// Do not edit manually

export interface Address {
  street: string
  city: string
  country: string
  zip_code: string
}

export interface CreatePostRequest {
  title: string
  content: string
  published: boolean
}

export interface CreateProfileRequest {
  bio: string
  avatar?: string
  address: Address
  preferences: Record<string, any>
  tags: Array<string>
}

export interface CreateUserRequest {
  name: string
  email: string
  password: string
  role: string
}

export interface ErrorResponse {
  error: string
  details: Array<ValidationError>
  code: string
}

export interface Post {
  id: number
  title: string
  content: string
  author_id: number
  published: boolean
  created_at: time.Time
}

export interface Profile {
  id: number
  user_id: number
  bio: string
  avatar?: string
  address: Address
  preferences: Record<string, any>
  tags: Array<string>
  metadata: Record<string, string>
  created_at: time.Time
}

export interface SearchRequest {
  query: string
  filters: Record<string, string>
  limit?: number
  offset?: number
}

export interface SearchResult {
  users: Array<User>
  posts: Array<Post>
  profiles: Array<Profile>
  total: number
}

export interface User {
  id: number
  email: string
  password_hash: string
  name: string
  role: time.Time
}

export interface ValidationError {
  field: string
  message: string
  value: any
}

