// Auto-generated TypeScript types from Go structs
// Generated by GoFlux type generation system
// Do not edit manually

export interface CreatePostRequest {
  content: string
  published: boolean
  title: string
  user_id: number
}

export interface CreateUserRequest {
  age: number
  email: string
  name: string
}

export interface DeletePostOutputBody {
  id: number
  message: string
}

export interface DeleteUserOutputBody {
  id: number
  message: string
}

export interface ErrorDetail {
  location?: string
  message?: string
  value?: unknown
}

export interface ErrorModel {
  detail?: string
  errors?: ErrorDetail[]
  instance?: string
  status?: number
  title?: string
  type?: string
}

export interface Post {
  content: string
  created_at: string
  id: number
  published: boolean
  title: string
  updated_at: string
  user?: User
  user_id: number
}

export interface UpdatePostRequest {
  content?: string
  published?: boolean
  title?: string
  user_id?: number
}

export interface UpdateUserRequest {
  age?: number
  email?: string
  name?: string
}

export interface User {
  age: number
  created_at: string
  email: string
  id: number
  name: string
  updated_at: string
}

